export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readTime: string;
  publishedAt: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: '3-months-postpartum',
    title: '3 Months Postpartum: What to Expect',
    excerpt: 'Three months postpartum is a turning point — but it does not always feel like one. Here is an honest guide to what is normal at 3 months for your body, your baby and your mental health.',
    category: 'Recovery',
    readTime: '9 min read',
    publishedAt: '2026-04-13',
  },
  {
    slug: 'how-to-increase-milk-supply',
    title: "How to Increase Milk Supply: What Actually Works (and What Doesn't)",
    excerpt: 'Worried your milk supply is dropping? This evidence-based guide covers every proven method to increase breast milk production — from feeding techniques to foods and pumping strategies.',
    category: 'Nutrition',
    readTime: '9 min read',
    publishedAt: '2026-04-12',
  },
  {
    slug: 'postpartum-meal-prep',
    title: 'Postpartum Meal Prep: How to Eat Well When You Have No Time',
    excerpt: 'Eating well after having a baby feels impossible when you can barely make a cup of tea. This practical guide to postpartum meal prep will change that — one batch cook at a time.',
    category: 'Nutrition',
    readTime: '8 min read',
    publishedAt: '2026-04-11',
  },
  {
    slug: 'postpartum-fitness',
    title: 'Postpartum Fitness: How to Rebuild Strength Safely After Birth',
    excerpt: 'Rebuilding fitness after having a baby is not about bouncing back — it is about building forward. Here is the honest, science-based guide to postpartum strength.',
    category: 'Fitness',
    readTime: '9 min read',
    publishedAt: '2026-04-10',
  },
  {
    slug: 'returning-to-work-after-maternity-leave',
    title: 'Returning to Work After Maternity Leave: A Practical Guide for New Mothers',
    excerpt: 'Going back to work after having a baby is one of the hardest transitions a mother faces. This honest, practical guide covers everything from breastfeeding at work to managing mum guilt.',
    category: 'Recovery',
    readTime: '8 min read',
    publishedAt: '2026-04-09',
  },
  {
    slug: 'postpartum-sex',
    title: 'Postpartum Sex: What to Expect When You Feel Ready',
    excerpt: 'Nobody gives you an honest guide to sex after having a baby. From physical changes to emotional readiness, here is everything you need to know — without the awkwardness.',
    category: 'Recovery',
    readTime: '8 min read',
    publishedAt: '2026-04-08',
  },
  {
    slug: 'postpartum-body-changes',
    title: 'Postpartum Body Changes Nobody Warns You About',
    excerpt: 'From night sweats to loose joints, the postpartum body goes through changes nobody prepares you for. Here is the honest guide to what is happening and why it is all normal.',
    category: 'Recovery',
    readTime: '9 min read',
    publishedAt: '2026-04-07',
  },
  {
    slug: 'newborn-sleep-schedule',
    title: 'Newborn Sleep Schedule: What to Really Expect in the First 3 Months',
    excerpt: 'Newborn sleep is chaotic, exhausting and completely normal. Here is an honest, month-by-month guide to what to expect — and how to survive it with your sanity intact.',
    category: 'Baby Health',
    readTime: '12 min read',
    publishedAt: '2026-04-06',
  },
  {
    slug: 'when-to-stop-breastfeeding',
    title: 'When to Stop Breastfeeding: A Gentle, Judgement-Free Guide to Weaning',
    excerpt: 'There is no single right time to stop breastfeeding. This honest, gentle guide covers every weaning option — from baby-led to mother-led — and how to make the transition easier.',
    category: 'Nutrition',
    readTime: '12 min read',
    publishedAt: '2026-04-05',
  },
  {
    slug: 'postpartum-depression-vs-baby-blues',
    title: 'Postpartum Depression vs Baby Blues: How to Tell the Difference',
    excerpt: 'Feeling overwhelmed after birth is normal — but how do you know when it is more than baby blues? Learn the real differences, the warning signs, and when to ask for help.',
    category: 'Recovery',
    readTime: '12 min read',
    publishedAt: '2026-04-04',
  },
  {
    slug: 'diastasis-recti',
    title: 'Diastasis Recti: What It Is, How to Check for It and How to Heal It',
    excerpt: 'Diastasis recti affects up to 60% of pregnant women. Learn what it actually is, how to check yourself at home, what makes it worse, and how to genuinely heal it.',
    category: 'Recovery',
    readTime: '15 min read',
    publishedAt: '2026-04-01',
  },
  {
    slug: 'breastfeeding-and-periods',
    title: 'Breastfeeding and Periods: When Does Your Cycle Return?',
    excerpt: 'Wondering when your period will return after birth? Whether you are breastfeeding or not, here is exactly what to expect and why everyone\'s timeline is different.',
    category: 'Recovery',
    readTime: '5 min read',
    publishedAt: '2026-04-01',
  },
  {
    slug: 'postpartum-hair-loss',
    title: 'Postpartum Hair Loss: Why It Happens and When It Stops',
    excerpt: 'Losing handfuls of hair after birth is normal but alarming. Learn exactly why postpartum hair loss happens, when it peaks, and when it stops completely.',
    category: 'Recovery',
    readTime: '12 min read',
    publishedAt: '2026-03-31',
  },
  {
    slug: "baby-growth-spurts",
    title: "Baby Growth Spurts: What They Are, When They Happen and How to Survive Them",
    excerpt: "Baby growth spurts can feel sudden and overwhelming. Learn the typical timeline, signs to look for, and how to support your baby through each one.",
    category: "Baby Health",
    readTime: "5 min read",
    publishedAt: "2026-03-28",
  },
  {
    slug: "postpartum-pelvic-floor-dysfunction",
    title: "Signs of Postpartum Pelvic Floor Dysfunction — And What To Do About Them",
    excerpt: "Leaking, heaviness, pain — these are signs of postpartum pelvic floor dysfunction. Learn to recognise them early and what steps to take to heal.",
    category: "Recovery",
    readTime: "10 min read",
    publishedAt: "2026-03-28",
  },
  {
    slug: "c-section-recovery-timeline",
    title: "C-Section Recovery: What to Expect Week by Week",
    excerpt: "A realistic week-by-week guide to C-section recovery — from hospital discharge through 12 weeks. What to expect, what to avoid, and when most women feel like themselves again.",
    category: "Recovery",
    readTime: "25 min read",
    publishedAt: "2026-03-15",
  },
  {
    slug: "postpartum-nutrition-guide",
    title: "Postpartum Nutrition: What to Eat to Heal, Recover and Thrive",
    excerpt: "A complete postpartum nutrition guide covering the key nutrients new mothers need for healing, breastfeeding and sustained energy in the fourth trimester.",
    category: "Nutrition",
    readTime: "15 min read",
    publishedAt: "2026-03-27",
  },
  {
    slug: "how-long-to-lose-baby-weight",
    title: "How Long Does It Take to Lose the Baby Weight? (An Honest Answer)",
    excerpt: "Most mothers wonder how long postpartum weight loss really takes. An honest, science-based answer with realistic timelines for breastfeeding and non-breastfeeding mothers.",
    category: "Recovery",
    readTime: "12 min read",
    publishedAt: "2026-03-27",
  },
  {
    slug: "safe-weight-loss-breastfeeding",
    title: "Is it Safe to Lose Weight While Breastfeeding?",
    excerpt: "Find out whether it's safe to lose weight while breastfeeding, how quickly you can lose weight postpartum, and what affects your milk supply.",
    category: "Nutrition",
    readTime: "5 min read",
    publishedAt: "2026-03-25",
  },
  {
    slug: "breastfeeding-calorie-needs",
    title: "How Many Extra Calories Do You Need When Breastfeeding?",
    excerpt: "Breastfeeding burns hundreds of extra calories a day. Learn how many calories you actually need, what affects your intake, and how to eat well for you and your baby.",
    category: "Nutrition",
    readTime: "4 min read",
    publishedAt: "2026-03-20",
  },
  {
    slug: "returning-to-exercise-after-birth",
    title: "A Gentle Guide to Returning to Exercise After Birth",
    excerpt: "When is it safe to exercise after giving birth? Learn the evidence-based timeline for returning to exercise after a vaginal birth or C-section.",
    category: "Fitness",
    readTime: "6 min read",
    publishedAt: "2026-03-15",
  },
  {
    slug: "pelvic-floor-after-birth",
    title: "What is the Pelvic Floor and Why Does it Matter After Birth?",
    excerpt: "Learn what the pelvic floor is, how birth affects it, and what you can do to support your recovery. Includes signs of pelvic floor dysfunction to watch for.",
    category: "Recovery",
    readTime: "5 min read",
    publishedAt: "2026-03-10",
  },
  {
    slug: "understanding-baby-growth-chart",
    title: "Understanding Your Baby's Growth Chart",
    excerpt: "Growth charts can feel confusing and worrying. Learn what percentiles actually mean, what WHO growth standards are, and when to talk to your doctor.",
    category: "Baby Health",
    readTime: "5 min read",
    publishedAt: "2026-03-05",
  },
];
